language: ruby
rvm:
  - "1.9.3"
before_install:
  - cd ..
  - git clone https://github.com/pfadipatria/hitobito.git
  - git clone https://github.com/pfadipatria/hitobito_patria.git
  - cd hitobito
install: bundle install
before_script:
  - rake db:create
  - rake db:setup:all
script:
  - rake
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec